# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: Oddyseuss's Website
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lectus elit, ultricies sit amet maximus eget, rhoncus sit amet augue. Etiam cursus, dolor commodo viverra sagittis, urna ante eleifend massa, a sagittis nisi ligula at libero. Quisque sed blandit velit. Donec nisi mi, rhoncus et suscipit ut, rutrum at massa. Aenean consequat lorem justo, sed aliquam velit consequat vel. Sed mi leo, porttitor id gravida ut, rhoncus ut nulla. Cras iaculis facilisis finibus. Sed nec egestas eros. Integer eu hendrerit elit. Morbi in risus enim. Integer gravida, metus sit amet cursus pharetra, sem magna viverra erat, eget finibus massa dolor at sapien. Praesent pellentesque a diam sed malesuada. Etiam porttitor pharetra eros, quis congue lorem. Praesent tempor eleifend purus id sollicitudin. Vivamus posuere ac elit ac finibus. Donec suscipit vitae risus at commodo. Aliquam vitae ante nulla. Aenean lobortis orci lorem. Donec quis ex vitae tellus rhoncus interdum eget et purus. Ut convallis lacus at risus molestie faucibus. Integer ac sapien nec dui consectetur cursus.
baseurl: "" # the subpath of your site, e.g. /blog
url: "Oddyseuss.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
